version: '3.8'

services:
  sales-bike-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales-bike-agent
    ports:
      - "8000:8000"
    environment:
      # LLM Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4-turbo-preview}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}

      # CRM API Configuration
      - CRM_API_URL=${CRM_API_URL:-https://api.example.com}
      - CRM_API_KEY=${CRM_API_KEY}

      # Application Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SESSION_TTL_MINUTES=${SESSION_TTL_MINUTES:-30}
      - MAX_CONVERSATION_TURNS=${MAX_CONVERSATION_TURNS:-20}

      # Vector Store Configuration
      - FAISS_INDEX_PATH=data/indices

      # Data Paths
      - PRODUCT_CATALOG_PATH=Data/product_catalog.json
      - FAQ_PATH=Data/faq.txt
    volumes:
      # Persist FAISS indices
      - faiss-indices:/app/data/indices
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health', timeout=5.0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  faiss-indices:
    driver: local
